### ISSUE TITLE
Consider removing the `WEB_MEMORY` env var

### ISSUE THREAD

**Issue by edmorley** [heroku/buildpacks-nodejs#781]
Currently the Node.js CNB sets not only the `WEB_CONCURRENCY` env var, but `WEB_MEMORY` too.

This differs from the Node.js classic buildpack, which sets `MEMORY_AVAILABLE` instead of `WEB_MEMORY`.

In addition, all of the classic buildpacks use a different strategy for a memory related env var:
- Node.js classic sets `MEMORY_AVAILABLE` (as above)
- Python classic currently sets `DYNO_RAM` (but I'm considering removing support for this in classic, and not adding to CNB at all)
- Ruby classic sets `HEROKU_RAM_LIMIT_MB` but only if the undocumented/deprecated `SENSIBLE_DEFAULTS` env var is set
- All other languages don't set anything

Given that the Node.js CNB env var name is net new, I think it would be best to remove it for now before too many people start relying on it, and wait until we standardise on the same name for all CNBs - or even if we want to set a memory related env var at all? (Or if we do want the env var, perhaps we shouldn't implement it in every buildpack, but at the platform or launcher layer, given the RAM env var is not language specific?). 

cc @colincasey @joshwlewis

**Comment by edmorley** [comment]
Ah true. It seems that the Node.js definition of `WEB_MEMORY` is "how much memory per process" not "how much memory available for the dyno". This wasn't clear to me from the naming of the env var alone.

**Comment by joshwlewis** [comment]
`WEB_MEMORY` has been a documented way to control concurrency for Node.js applications for quite a while: https://devcenter.heroku.com/articles/node-concurrency#tuning-the-concurrency-level`. I've seen it used by customers here and there in the past. It's mostly in the CNB to maintain that compatibility.

It's kind of nice, because customers can use it to tweak concurrency, but still get some value if they decide to scale vertically later. Manually setting`WEB_CONCURRENCY` would mean manually setting it again for any vertical scaling. Theoretically, at least -- it's obviously flawed since it totally ignores CPU.

I'm not too attached to it. However, until some other solution exists (say some standardized naming, or some platform config), I don't think removing it is worth adding a migration path.

**Comment by edmorley** [comment]
The only reason I suggested removing it, is since I thought (a) it was net new, (b) that it was the new name for `MEMORY_AVAILABLE`.

Since it's neither new, nor does it do the same thing as `MEMORY_AVAILABLE`, then I agree it should be left in.

The naming (leading to confusion about what the env vars actually do) and inconsistency between languages still leaves a lot to be desired, but I guess that's something to think about longer term :-)
